# Generated by Django 5.1.4 on 2025-01-19 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Status name (e.g., Scheduled, Completed)', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of the status')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the test', max_length=100)),
                ('date', models.DateField(help_text='Date of the test (can include future dates)')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the test was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the test was last updated')),
                ('status', models.ForeignKey(help_text='Current status of the test', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests', to='testprogress.teststatus')),
            ],
        ),
    ]
