# Generated by Django 5.1.4 on 2025-01-23 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testprogress', '0002_teststatus_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teststatus',
            name='description',
        ),
        migrations.AddField(
            model_name='test',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
