# Generated by Django 5.1.4 on 2026-03-13 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('center', '0018_alter_batch_unique_together_remove_batch_session'),
        ('inquiry_followup', '0014_fill_inquiry_session_fallback'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(editable=False, max_length=16, unique=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('auto_release', models.BooleanField(default=False, help_text='If enabled, the report is immediately visible to the parent once the test is submitted.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sat_assignments', to='inquiry_followup.inquiry')),
            ],
        ),
        migrations.CreateModel(
            name='TestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attempt', to='sat.testassignment')),
            ],
        ),
        migrations.CreateModel(
            name='TestPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('time_limit', models.PositiveIntegerField(default=60, help_text='Minutes')),
                ('marks_per_correct', models.PositiveIntegerField(default=1, help_text='Marks awarded per correct answer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sat_papers', to='center.classname')),
            ],
        ),
        migrations.AddField(
            model_name='testassignment',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='sat.testpaper'),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('text', models.TextField(help_text='Supports Markdown: **bold**, *italic*, `code`')),
                ('option_a', models.CharField(max_length=500)),
                ('option_b', models.CharField(max_length=500)),
                ('option_c', models.CharField(max_length=500)),
                ('option_d', models.CharField(max_length=500)),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('difficulty', models.CharField(choices=[('L1', 'L1 – Easy'), ('L2', 'L2 – Moderate'), ('L3', 'L3 – Hard')], default='L2', max_length=2)),
                ('subject_tag', models.CharField(choices=[('Math', 'Mathematics'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Science', 'General Science'), ('Biology', 'Biology'), ('English', 'English'), ('Reasoning', 'Logical Reasoning'), ('Other', 'Other')], default='Other', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='sat.testpaper')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_marks', models.PositiveIntegerField(default=0)),
                ('max_marks', models.PositiveIntegerField(default=0)),
                ('subject_scores', models.JSONField(default=dict, help_text='{"Math": {"obtained": 5, "max": 10, "correct": 5, "attempted": 8}}')),
                ('difficulty_scores', models.JSONField(default=dict, help_text='{"L1": {"obtained": 3, "max": 5, "correct": 3, "attempted": 4}}')),
                ('visibility', models.CharField(choices=[('hold', 'Hold – Admin only'), ('shared', 'Shared – Visible via link')], default='hold', max_length=10)),
                ('report_token', models.CharField(editable=False, max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='sat.testattempt')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, null=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('marks_obtained', models.PositiveSmallIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='sat.question')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='sat.testattempt')),
            ],
            options={
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
