# Generated by Django 5.1.4 on 2026-03-13 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sat', '0002_add_option_e'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('Conceptual', 'Conceptual'), ('Application', 'Application Based'), ('Numerical', 'Numerical Type'), ('Analytical', 'Logical / Analytical Thinking'), ('Factual', 'Factual / Memory Based'), ('Other', 'Other')], default='Conceptual', max_length=20),
        ),
    ]
