# Generated by Django 5.1.4 on 2026-03-13 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sat', '0003_add_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='type_scores',
            field=models.JSONField(default=dict, help_text='{"Conceptual": {"obtained": 5, "max": 10, "correct": 5, "attempted": 8}}'),
        ),
    ]
