# Generated by Django 5.1.4 on 2026-04-03 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_campaign_color'),
        ('sat', '0004_add_type_scores'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolTestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('session_code', models.CharField(editable=False, max_length=10, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_test_sessions', to='marketing.campaign')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_sessions', to='sat.testpaper')),
            ],
        ),
        migrations.AddField(
            model_name='testassignment',
            name='school_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='sat.schooltestsession'),
        ),
    ]
