# Generated by Django 5.1.4 on 2026-04-03 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sat', '0005_schooltestsession_testassignment_school_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schooltestsession',
            name='paper',
            field=models.ForeignKey(blank=True, help_text="Leave blank to auto-select the paper based on each student's chosen class.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_sessions', to='sat.testpaper'),
        ),
    ]
