# Generated by Django 5.1.4 on 2026-04-06 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sat', '0006_alter_schooltestsession_paper'),
    ]

    operations = [
        migrations.AddField(
            model_name='testattempt',
            name='auto_submitted',
            field=models.BooleanField(default=False, help_text='True when the client timer triggered submission (not student action).'),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='fullscreen_exit_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='late_by_seconds',
            field=models.IntegerField(blank=True, help_text='Seconds past the time limit at submission. Negative means early.', null=True),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='question_order',
            field=models.JSONField(default=list, help_text='Shuffled list of Question IDs assigned at attempt creation.'),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='tab_switch_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
