# Generated by Django 5.1.4 on 2025-02-16 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry_followup', '0003_followup_created_at_followup_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='followup_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
