# Generated by Django 5.1.4 on 2025-03-08 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry_followup', '0005_alter_inquiry_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='existing_member',
            field=models.BooleanField(default=False),
        ),
    ]
