# Generated by Django 5.1.4 on 2025-03-09 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0014_test_no_of_questions_test_total_max_marks_and_more'),
        ('inquiry_followup', '0006_inquiry_existing_member'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='lead_quality',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Real', 'Real'), ('Fake', 'Fake')], default='Pending', max_length=10),
        ),
        migrations.CreateModel(
            name='StationaryPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stationary_partner', to='center.center')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stationary_partner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='inquiry',
            name='stationary_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='inquiry_followup.stationarypartner'),
        ),
    ]
