# Generated by Django 5.1.4 on 2025-03-11 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry_followup', '0007_inquiry_lead_quality_stationarypartner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiry',
            name='lead_quality',
        ),
        migrations.AddField(
            model_name='inquiry',
            name='lead_type',
            field=models.CharField(choices=[('Unverified', 'Unverified'), ('Verified', 'Verified'), ('Fake', 'Fake')], default='Unverified', max_length=20),
        ),
        migrations.AddField(
            model_name='stationarypartner',
            name='earned_commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='stationarypartner',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='stationarypartner',
            name='monthly_incentive',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='stationarypartner',
            name='pending_commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='stationarypartner',
            name='total_commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='PartnerPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_mode', models.CharField(blank=True, choices=[('Cash', 'Cash'), ('UPI', 'UPI'), ('Net Banking', 'Net Banking'), ('Credit Card', 'Credit Card'), ('Debit Card', 'Debit Card'), ('Auto Debit', 'Auto Debit')], max_length=255, null=True)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remark', models.TextField()),
                ('date', models.DateField()),
                ('paid_by', models.CharField(max_length=255)),
                ('type_of_payment', models.CharField(choices=[('Monthly Payment', 'Monthly Payment'), ('Incentive', 'Incentive')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stationary_partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='inquiry_followup.stationarypartner')),
            ],
        ),
    ]
