# Generated by Django 5.1.4 on 2026-03-11 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry_followup', '0009_stationarypartner_lead_incentive'),
        ('registration', '0102_alter_feedetails_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='registration.academicsession'),
        ),
    ]
