# Generated by Django 5.1.4 on 2026-03-20 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry_followup', '0015_referralsource'),
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='marketing.campaign'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='intent',
            field=models.CharField(blank=True, choices=[('single_subject', 'Single Subject'), ('full_package', 'Full Package')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='lead_quality',
            field=models.CharField(blank=True, choices=[('hot', 'Hot'), ('warm', 'Warm'), ('cold', 'Cold')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='parent_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='parent_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='referrer_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='referrer_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterUniqueTogether(
            name='referralsource',
            unique_together={('name', 'category')},
        ),
        migrations.AddField(
            model_name='inquiry',
            name='referral_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='inquiry_followup.referralsource'),
        ),
    ]
