# Generated by Django 5.1.4 on 2026-03-21 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry_followup', '0017_migrate_referral_to_referralsource'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='current_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_inquiries', to='inquiry_followup.followupstatus'),
        ),
    ]
