# Generated by Django 5.1.4 on 2026-03-24 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry_followup', '0018_add_current_status_to_inquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('utm_slug', models.SlugField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='inquiry',
            name='assigned_counsellor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_inquiries', to='inquiry_followup.admissioncounselor'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='caller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='called_inquiries', to='inquiry_followup.admissioncounselor'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='inquiry_origin',
            field=models.CharField(choices=[('walk_in', 'Walk-In'), ('organic_call', 'Organic Call'), ('campaign', 'Campaign')], default='organic_call', max_length=20),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='sales_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='inquiry_followup.salesperson'),
        ),
    ]
