# Generated by Django 5.1.4 on 2026-03-24 07:12

from django.db import migrations


def add_post_test_status(apps, schema_editor):
    FollowUpStatus = apps.get_model('inquiry_followup', 'FollowUpStatus')
    last = FollowUpStatus.objects.order_by('-order').first()
    next_order = (last.order + 1) if last else 100
    FollowUpStatus.objects.get_or_create(
        name='Post-Test',
        defaults={'order': next_order, 'color': '#6366f1'},
    )


def remove_post_test_status(apps, schema_editor):
    FollowUpStatus = apps.get_model('inquiry_followup', 'FollowUpStatus')
    FollowUpStatus.objects.filter(name='Post-Test').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry_followup', '0019_salesperson_inquiry_ownership'),
    ]

    operations = [
        migrations.RunPython(add_post_test_status, reverse_code=remove_post_test_status),
    ]
