# Generated by Django 5.1.4 on 2026-04-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry_followup', '0021_salesperson_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='admission_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
