# Generated by Django 5.1.4 on 2026-03-20 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0105_remove_courseoffering_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('channel', models.CharField(choices=[('google_ads', 'Google Ads'), ('meta', 'Meta (FB/IG)'), ('youtube', 'YouTube'), ('offline', 'Offline'), ('whatsapp', 'WhatsApp Broadcast'), ('other', 'Other')], max_length=50)),
                ('utm_source', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='registration.academicsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
