# Generated by Django 5.1.4 on 2026-03-20 10:01

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default='#6c757d', image_field=None, max_length=25, samples=None),
        ),
    ]
