# Generated by Django 5.1.4 on 2025-08-02 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0049_batch_end_date_batch_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('PTM', 'PTM'), ('MENTOR', 'Mentor Session')], max_length=20)),
                ('date', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='registration.student')),
            ],
            options={
                'unique_together': {('student', 'action', 'date')},
            },
        ),
    ]
