# Generated by Django 5.1.4 on 2025-08-02 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recommendation',
        ),
    ]
