# Generated by Django 5.1.4 on 2025-02-07 11:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('center', '0014_test_no_of_questions_test_total_max_marks_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('book_fees', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('uniform_fees', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cab_fees', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tuition_fees', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_fees', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('remaining_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('dob', models.DateField()),
                ('doj', models.DateField(blank=True, null=True)),
                ('class_enrolled', models.CharField(max_length=100)),
                ('marksheet_submitted', models.BooleanField(default=False)),
                ('sat_score', models.PositiveIntegerField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('last_year_marks_details', models.TextField(blank=True, null=True)),
                ('aadhar_card_number', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='center.classname')),
                ('subjects', models.ManyToManyField(blank=True, related_name='students', to='center.subject')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registered_student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ParentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('father_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=255, null=True)),
                ('father_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('mother_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_details', to='registration.student')),
            ],
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
                ('paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fee_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='registration.feedetails')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='registration.student')),
            ],
        ),
        migrations.AddField(
            model_name='feedetails',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='registration.student'),
        ),
        migrations.CreateModel(
            name='TransportDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transport', to='registration.student')),
            ],
        ),
    ]
