# Generated by Django 5.1.4 on 2025-02-07 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0014_test_no_of_questions_test_total_max_marks_and_more'),
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='class_enrolled',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='center.classname'),
        ),
        migrations.AlterField(
            model_name='student',
            name='school_name',
            field=models.CharField(max_length=100),
        ),
    ]
