# Generated by Django 5.1.4 on 2025-02-25 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_alter_feedetails_book_fees_alter_feedetails_cab_fees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='installment',
            name='label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='installment',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('UPI', 'UPI'), ('Net Banking', 'Net Banking'), ('Credit Card', 'Credit Card'), ('Debit Card', 'Debit Card'), ('Auto Debit', 'Auto Debit')], max_length=255, null=True),
        ),
    ]
