# Generated by Django 5.1.4 on 2025-03-01 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_installment_label_installment_payment_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedetails',
            old_name='book_fees',
            new_name='registration_fee',
        ),
        migrations.RemoveField(
            model_name='feedetails',
            name='uniform_fees',
        ),
    ]
