# Generated by Django 5.1.4 on 2025-03-01 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_rename_book_fees_feedetails_registration_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.CharField(blank=True, choices=[('CBSE', 'CBSE'), ('NEET', 'NEET'), ('JEE', 'JEE')], max_length=10, null=True),
        ),
    ]
