# Generated by Django 5.1.4 on 2025-03-03 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_student_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='program_duration',
            field=models.CharField(blank=True, choices=[('1 Year', '1 Year'), ('2 Year', '2 Year'), ('3 Year', '3 Year')], default='1 Year', max_length=10),
        ),
    ]
