# Generated by Django 5.1.4 on 2025-03-03 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_student_program_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedetails',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
