# Generated by Django 5.1.4 on 2025-03-05 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_feedetails_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedetails',
            name='book_fees',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
