# Generated by Django 5.1.4 on 2025-03-06 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_feedetails_book_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedetails',
            name='book_discount',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feedetails',
            name='registration_discount',
            field=models.BooleanField(default=False),
        ),
    ]
