# Generated by Django 5.1.4 on 2025-03-06 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_feedetails_book_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(blank=True, choices=[('CBSE', 'CBSE'), ('NEET', 'NEET'), ('JEE', 'JEE'), ('Apex Course', 'Apex Course'), ('Momentum Course', 'Momentum Course'), ('Foundation Course', 'Foundation Course')], max_length=65, null=True),
        ),
    ]
