# Generated by Django 5.1.4 on 2025-04-01 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0014_test_no_of_questions_test_total_max_marks_and_more'),
        ('registration', '0011_alter_student_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installment',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('UPI', 'UPI'), ('Net Banking', 'Net Banking'), ('Credit Card', 'Credit Card'), ('Debit Card', 'Debit Card'), ('Auto Debit', 'Auto Debit'), ('Cheque', 'Cheque')], max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='center.classname')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='center.section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='center.subject')),
            ],
            options={
                'unique_together': {('class_name', 'section', 'subject')},
            },
        ),
        migrations.AddField(
            model_name='student',
            name='batches',
            field=models.ManyToManyField(blank=True, related_name='students', to='registration.batch'),
        ),
    ]
