# Generated by Django 5.1.4 on 2025-04-05 10:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0014_attendance_homework'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 4, 4, 10, 16, 21, 458484, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homework',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 4, 4, 10, 16, 30, 993027, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='installment',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('UPI', 'UPI'), ('Net Banking', 'Net Banking'), ('Credit Card', 'Credit Card'), ('Debit Card', 'Debit Card'), ('Auto Debit', 'Auto Debit'), ('Cheque', 'Cheque'), ('UPI + Cash', 'UPI + Cash')], max_length=255, null=True),
        ),
    ]
