# Generated by Django 5.1.4 on 2025-05-01 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0020_remark_alter_testquestion_test_questionresponse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
