# Generated by Django 5.1.4 on 2025-05-01 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0022_alter_batch_end_time_alter_batch_start_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Days',
            },
        ),
        migrations.AddField(
            model_name='batch',
            name='days',
            field=models.ManyToManyField(blank=True, related_name='batches', to='registration.day'),
        ),
    ]
