# Generated by Django 5.1.4 on 2025-05-04 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0026_transportmode_transportperson_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transportperson',
            old_name='vehicle_id',
            new_name='person_id',
        ),
    ]
