# Generated by Django 5.1.4 on 2025-05-12 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0027_rename_vehicle_id_transportperson_person_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='installment',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
