# Generated by Django 5.1.4 on 2025-05-21 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0028_installment_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='negative_marking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test',
            name='objective',
            field=models.BooleanField(default=False),
        ),
    ]
