# Generated by Django 5.1.4 on 2025-05-21 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0029_test_negative_marking_test_objective'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='negative_marking',
        ),
    ]
