# Generated by Django 5.1.4 on 2025-06-03 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0032_action_mentorremark_actionsuggested_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportNegative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReportPositive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='mentorremark',
            name='mentor_negative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentor_remarks', to='registration.reportnegative'),
        ),
        migrations.AddField(
            model_name='mentorremark',
            name='parent_negative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_remarks', to='registration.reportnegative'),
        ),
        migrations.AddField(
            model_name='mentorremark',
            name='mentor_positive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentor_remarks', to='registration.reportpositive'),
        ),
        migrations.AddField(
            model_name='mentorremark',
            name='parent_positive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_remarks', to='registration.reportpositive'),
        ),
    ]
