# Generated by Django 5.1.4 on 2025-06-03 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0033_reportnegative_reportpositive_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorremark',
            name='mentor_remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
