# Generated by Django 5.1.4 on 2025-06-03 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0034_alter_mentorremark_mentor_remark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentorremark',
            name='mentor_negative',
        ),
        migrations.RemoveField(
            model_name='mentorremark',
            name='mentor_positive',
        ),
        migrations.RemoveField(
            model_name='mentorremark',
            name='parent_negative',
        ),
        migrations.RemoveField(
            model_name='mentorremark',
            name='parent_positive',
        ),
        migrations.AddField(
            model_name='mentorremark',
            name='mentor_negative',
            field=models.ManyToManyField(blank=True, related_name='mentor_remarks', to='registration.reportnegative'),
        ),
        migrations.AddField(
            model_name='mentorremark',
            name='mentor_positive',
            field=models.ManyToManyField(blank=True, related_name='mentor_remarks', to='registration.reportpositive'),
        ),
        migrations.AddField(
            model_name='mentorremark',
            name='parent_negative',
            field=models.ManyToManyField(blank=True, related_name='parent_remarks', to='registration.reportnegative'),
        ),
        migrations.AddField(
            model_name='mentorremark',
            name='parent_positive',
            field=models.ManyToManyField(blank=True, related_name='parent_remarks', to='registration.reportpositive'),
        ),
    ]
