# Generated by Django 5.1.4 on 2025-06-06 12:13

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0035_remove_mentorremark_mentor_negative_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=None, verbose_name='Color'),
        ),
    ]
