# Generated by Django 5.1.4 on 2025-06-12 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0038_transportattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportattendance',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transport_attendance', to='registration.transportperson'),
        ),
    ]
