# Generated by Django 5.1.4 on 2025-06-15 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0039_transportattendance_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='test_type',
            field=models.CharField(choices=[('Retest', 'Retest'), ('Regular', 'Regular'), ('Mock', 'Mock'), ('Final', 'Final'), ('Revision', 'Revision'), ('Diagnostic', 'Diagnostic'), ('Practice', 'Practice'), ('Other', 'Other')], default='Regular', max_length=20),
        ),
    ]
