# Generated by Django 5.1.4 on 2025-06-16 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0040_testresult_test_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='test_type',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Retest', 'Retest')], default='Regular', max_length=20),
        ),
    ]
