# Generated by Django 5.1.4 on 2025-06-16 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0041_alter_testresult_test_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='previous_marks',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
