# Generated by Django 5.1.4 on 2025-06-18 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0042_testresult_previous_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportattendance',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
