# Generated by Django 5.1.4 on 2025-06-18 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0043_transportattendance_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportattendance',
            name='capacity',
        ),
        migrations.AddField(
            model_name='transportperson',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
