# Generated by Django 5.1.4 on 2025-06-25 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0044_remove_transportattendance_capacity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentBatchLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_links', to='registration.batch')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_links', to='registration.student')),
            ],
            options={
                'unique_together': {('student', 'batch')},
            },
        ),
    ]
