# Generated by Django 5.1.4 on 2025-07-17 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0047_studentbatchlink_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='installment',
            options={'ordering': ['due_date']},
        ),
    ]
