# Generated by Django 5.1.4 on 2025-08-02 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0050_recommendation_mentorremark_recommendation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recommendation',
            unique_together=set(),
        ),
    ]
