# Generated by Django 5.1.4 on 2025-08-13 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0051_alter_recommendation_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTestRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('remark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_remarks', to='registration.remark')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_remarks', to='registration.student')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_remarks', to='registration.test')),
            ],
            options={
                'unique_together': {('student', 'test', 'remark')},
            },
        ),
    ]
