# Generated by Django 5.1.4 on 2025-08-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0052_studenttestremark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenttestremark',
            name='remark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
