# Generated by Django 5.1.4 on 2025-08-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0053_alter_studenttestremark_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenttestremark',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
