# Generated by Django 5.1.4 on 2025-08-13 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0054_alter_studenttestremark_remark'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studenttestremark',
            unique_together={('student', 'test')},
        ),
        migrations.RemoveField(
            model_name='studenttestremark',
            name='count',
        ),
    ]
