# Generated by Django 5.1.4 on 2025-08-21 07:28

from django.db import migrations

def remove_duplicate_attendance(apps, schema_editor):
    Attendance = apps.get_model('registration', 'Attendance')
    from django.db.models import Count

    # Get all (student, batch, date, type) combinations that are duplicated
    duplicates = (
        Attendance.objects
        .values('student_id', 'batch_id', 'date')
        .annotate(count=Count('id'))
        .filter(count__gt=1)
    )

    count = 0    

    for dup in duplicates:
        # Get all matching records
        records = Attendance.objects.filter(
            student_id=dup['student_id'],
            batch_id=dup['batch_id'],
            date=dup['date'],
        ).order_by('-updated_at')

        to_keep = records.first()
        # Delete the rest
        count += records.exclude(id=to_keep.id).count()
        records.exclude(id=to_keep.id).delete()
    print(f"Removed {count} duplicate attendance records.")

class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0055_alter_studenttestremark_unique_together_and_more'),
    ]

    operations = [
        migrations.RunPython(remove_duplicate_attendance),
    ]
