# Generated by Django 5.1.4 on 2025-08-21 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0056_auto_20250821_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='type',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Retest', 'Retest'), ('Test', 'Test'), ('Extra Class', 'Extra Class')], default='Regular', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'batch', 'date', 'type')},
        ),
    ]
