# Generated by Django 5.1.4 on 2025-08-22 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0057_attendance_type_alter_attendance_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='type',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Retest', 'Retest'), ('Test', 'Test'), ('Extra Class', 'Extra Class'), ('Personal Class', 'Personal Class'), ('Practice Session', 'Practice Session')], default='Regular', max_length=20),
        ),
    ]
