# Generated by Django 5.1.4 on 2026-01-14 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0059_studentremark'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Eg: 2025-26', max_length=20, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=False, help_text='Only one session should be active at a time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.AlterField(
            model_name='attendance',
            name='type',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Remedial', 'Remedial'), ('Retest', 'Retest'), ('Test', 'Test'), ('Extra Class', 'Extra Class'), ('Personal Class', 'Personal Class'), ('Practice Session', 'Practice Session')], default='Regular', max_length=20),
        ),
    ]
