# Generated by Django 5.1.4 on 2026-01-14 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0015_remove_homework_batch_remove_homework_student_and_more'),
        ('registration', '0060_academicsession_alter_attendance_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(blank=True, choices=[('CBSE', 'CBSE'), ('NEET', 'NEET'), ('JEE', 'JEE'), ('Apex Course', 'Apex Course'), ('Momentum Course', 'Momentum Course'), ('Foundation Course', 'Foundation Course')], max_length=65, null=True)),
                ('program_duration', models.CharField(choices=[('1 Year', '1 Year'), ('2 Year', '2 Year'), ('3 Year', '3 Year')], default='1 Year', max_length=10)),
                ('active', models.BooleanField(default=True, help_text='Active enrollment for this session')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='center.classname')),
                ('promoted_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promoted_to', to='registration.studentenrollment')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='registration.academicsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='registration.student')),
                ('subjects', models.ManyToManyField(blank=True, related_name='enrollments', to='center.subject')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('student', 'session')},
            },
        ),
    ]
