# Generated by Django 5.1.4 on 2026-01-16 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0018_alter_batch_unique_together_remove_batch_session'),
        ('registration', '0062_backfill_student_enrollments'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='batch',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='batch',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='registration.academicsession'),
        ),
        migrations.AlterUniqueTogether(
            name='batch',
            unique_together={('class_name', 'section', 'subject', 'session')},
        ),
    ]
