# Generated by Django 5.1.4 on 2026-01-16 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0064_backfill_batch_sessions'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_links', to='registration.batch')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_links', to='registration.studentenrollment')),
            ],
            options={
                'unique_together': {('enrollment', 'batch')},
            },
        ),
    ]
