# Generated by Django 5.1.4 on 2026-01-16 07:51

from django.db import migrations


def migrate_batches(apps, schema_editor):
    Student = apps.get_model('registration', 'Student')
    StudentEnrollment = apps.get_model('registration', 'StudentEnrollment')
    EnrollmentBatch = apps.get_model('registration', 'EnrollmentBatch')

    for student in Student.objects.all():

        enrollment = StudentEnrollment.objects.filter(
            student=student,
            session__is_active=True
        ).first()

        if not enrollment:
            continue

        for batch in student.batches.all():
            EnrollmentBatch.objects.get_or_create(
                enrollment=enrollment,
                batch=batch
            )


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0065_enrollmentbatch'),
    ]

    operations = [
        migrations.RunPython(migrate_batches, migrations.RunPython.noop),
    ]