# Generated by Django 5.1.4 on 2026-01-16 08:53

from django.db import migrations

def migrate_attendance(apps, schema_editor):
    Attendance = apps.get_model('registration', 'Attendance')
    StudentEnrollment = apps.get_model('registration', 'StudentEnrollment')

    for att in Attendance.objects.all():

        enrollment = StudentEnrollment.objects.filter(
            student=att.student,
            session__is_active=True
        ).first()

        if enrollment:
            att.enrollment = enrollment
            att.save(update_fields=['enrollment'])

class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0067_attendance_enrollment'),
    ]

    operations = [
        migrations.RunPython(migrate_attendance, migrations.RunPython.noop),
    ]

