# Generated by Django 5.1.4 on 2026-01-16 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0068_migrate_attendance_to_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedetails',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='registration.studentenrollment'),
        ),
    ]
