# Generated by Django 5.1.4 on 2026-01-16 09:03

from django.db import migrations

def migrate_fees(apps, schema_editor):
    Fees = apps.get_model('registration', 'FeeDetails')
    StudentEnrollment = apps.get_model('registration', 'StudentEnrollment')

    for fee in Fees.objects.all():

        enrollment = StudentEnrollment.objects.filter(
            student=fee.student,
            session__is_active=True
        ).first()

        if enrollment:
            fee.enrollment = enrollment
            fee.save(update_fields=['enrollment'])


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0069_feedetails_enrollment'),
    ]

    operations = [
        migrations.RunPython(migrate_fees, migrations.RunPython.noop),
    ]
