# Generated by Django 5.1.4 on 2026-01-16 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0070_migrate_fees_to_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='registration.studentenrollment'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='registration.studentenrollment'),
        ),
    ]
