# Generated by Django 5.1.4 on 2026-01-16 13:35

from django.db import migrations

def migrate_homework(apps, schema_editor):
    Homework = apps.get_model('registration', 'Homework')
    StudentEnrollment = apps.get_model('registration', 'StudentEnrollment')

    for hw in Homework.objects.all():
        enrollment = StudentEnrollment.objects.filter(
            student=hw.student,
            session__is_active=True
        ).first()

        if enrollment:
            hw.enrollment = enrollment
            hw.save(update_fields=['enrollment'])


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0071_homework_enrollment_alter_attendance_enrollment'),
    ]

    operations = [
        migrations.RunPython(migrate_homework, migrations.RunPython.noop),
    ]