# Generated by Django 5.1.4 on 2026-01-17 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0072_migrate_homework'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentdetails',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transport_details', to='registration.studentenrollment'),
        ),
    ]
