# Generated by Django 5.1.4 on 2026-01-17 12:54

from django.db import migrations


def migrate_parentdetails(apps, schema_editor):
    ParentDetails = apps.get_model('registration', 'ParentDetails')
    StudentEnrollment = apps.get_model('registration', 'StudentEnrollment')

    for t in ParentDetails.objects.all():
        enrollment = StudentEnrollment.objects.filter(
            student=t.student,
            session__is_active=True
        ).first()

        if enrollment:
            t.enrollment = enrollment
            t.save(update_fields=['enrollment'])



class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0073_parentdetails_enrollment'),
    ]

    operations = [
        migrations.RunPython(migrate_parentdetails, reverse_code=migrations.RunPython.noop),
    ]
