# Generated by Django 5.1.4 on 2026-01-17 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0074_migrate_ParentDetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='installment',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='registration.studentenrollment'),
        ),
    ]
