# Generated by Django 5.1.4 on 2026-01-17 12:59

from django.db import migrations


def migrate_installments(apps, schema_editor):
    Installment = apps.get_model('registration', 'Installment')
    StudentEnrollment = apps.get_model('registration', 'StudentEnrollment')

    for inst in Installment.objects.all():
        enrollment = StudentEnrollment.objects.filter(
            student=inst.student,
            session__is_active=True
        ).first()

        if enrollment:
            inst.enrollment = enrollment
            inst.save(update_fields=['enrollment'])

class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0075_installment_enrollment'),
    ]

    operations = [
        migrations.RunPython(migrate_installments, reverse_code=migrations.RunPython.noop),
    ]
