# Generated by Django 5.1.4 on 2026-01-17 13:02

from django.db import migrations

def migrate_transport(apps, schema_editor):
    TransportDetails = apps.get_model('registration', 'TransportDetails')
    StudentEnrollment = apps.get_model('registration', 'StudentEnrollment')

    for t in TransportDetails.objects.all():
        enrollment = StudentEnrollment.objects.filter(
            student=t.student,
            session__is_active=True
        ).first()

        if enrollment:
            t.enrollment = enrollment
            t.save(update_fields=['enrollment'])



class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0078_transportdetails_enrollment'),
    ]

    operations = [
        migrations.RunPython(migrate_transport, reverse_code=migrations.RunPython.noop),
    ]
