# Generated by Django 5.1.4 on 2026-01-17 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0081_migrate_TestResult'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionresponse',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='registration.studentenrollment'),
        ),
    ]
