# Generated by Django 5.1.4 on 2026-01-17 13:16

from django.db import migrations

from registration.models import TransportDetails


def migrate_question_responses(apps, schema_editor):
    QuestionResponse = apps.get_model('registration', 'QuestionResponse')
    StudentEnrollment = apps.get_model('registration', 'StudentEnrollment')

    for t in QuestionResponse.objects.all():
        enrollment = StudentEnrollment.objects.filter(
            student=t.student,
            session__is_active=True
        ).first()

        if enrollment:
            t.enrollment = enrollment
            t.save(update_fields=['enrollment'])



class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0082_questionresponse_enrollment'),
    ]

    operations = [
        migrations.RunPython(migrate_question_responses, reverse_code=migrations.RunPython.noop),
    ]
