# Generated by Django 5.1.4 on 2026-01-17 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0083_migrate_QuestionResponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='remarkcount',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remark_count', to='registration.studentenrollment'),
        ),
    ]
