# Generated by Django 5.1.4 on 2026-01-17 13:22

from django.db import migrations

def migrate_remark_count(apps, schema_editor):
    RemarkCount = apps.get_model('registration', 'RemarkCount')
    StudentEnrollment = apps.get_model('registration', 'StudentEnrollment')

    for t in RemarkCount.objects.all():
        enrollment = StudentEnrollment.objects.filter(
            student=t.student,
            session__is_active=True
        ).first()

        if enrollment:
            t.enrollment = enrollment
            t.save(update_fields=['enrollment'])


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0084_remarkcount_enrollment'),
    ]

    operations = [
        migrations.RunPython(migrate_remark_count, reverse_code=migrations.RunPython.noop),
    ]