# Generated by Django 5.1.4 on 2026-01-17 13:32

from django.db import migrations


def migrate_mentorship(apps, schema_editor):
    Mentorship = apps.get_model('registration', 'Mentorship')
    StudentEnrollment = apps.get_model('registration', 'StudentEnrollment')

    for m in Mentorship.objects.all():
        enrollment = StudentEnrollment.objects.filter(
            student=m.student,
            session__is_active=True
        ).first()

        if enrollment:
            m.enrollment = enrollment
            m.save(update_fields=['enrollment'])

class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0086_mentorship_enrollment'),
    ]

    operations = [
        migrations.RunPython(migrate_mentorship, reverse_code=migrations.RunPython.noop),
    ]
