# Generated by Django 5.1.4 on 2026-01-17 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0087_migrate_Mentorship'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentremark',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_remarks', to='registration.studentenrollment'),
        ),
    ]
