# Generated by Django 5.1.4 on 2026-01-17 13:57

from django.db import migrations

from registration.models import Mentorship

def migrate_studentremark(apps, schema_editor):
    StudentRemark = apps.get_model('registration', 'StudentRemark')
    StudentEnrollment = apps.get_model('registration', 'StudentEnrollment')

    for m in StudentRemark.objects.all():
        enrollment = StudentEnrollment.objects.filter(
            student=m.student,
            session__is_active=True
        ).first()

        if enrollment:
            m.enrollment = enrollment
            m.save(update_fields=['enrollment'])

class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0088_studentremark_enrollment'),
    ]

    operations = [
        migrations.RunPython(migrate_studentremark, reverse_code=migrations.RunPython.noop),
    ]
