# Generated by Django 5.1.4 on 2026-01-17 14:00

from django.db import migrations

def migrate_studenttestremark(apps, schema_editor):
    StudentTestRemark = apps.get_model('registration', 'StudentTestRemark')
    StudentEnrollment = apps.get_model('registration', 'StudentEnrollment')

    for m in StudentTestRemark.objects.all():
        enrollment = StudentEnrollment.objects.filter(
            student=m.student,
            session__is_active=True
        ).first()

        if enrollment:
            m.enrollment = enrollment
            m.save(update_fields=['enrollment'])

class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0090_studenttestremark_enrollment'),
    ]

    operations = [
        migrations.RunPython(migrate_studenttestremark, reverse_code=migrations.RunPython.noop),
    ]