# Generated by Django 5.1.4 on 2026-01-17 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0091_migrate_StudentTestRemark'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportattendance',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transport_attendances', to='registration.studentenrollment'),
        ),
    ]
