# Generated by Django 5.1.4 on 2026-01-17 14:03

from django.db import migrations

def migrate_transportattendance(apps, schema_editor):
    TransportAttendance = apps.get_model('registration', 'TransportAttendance')
    StudentEnrollment = apps.get_model('registration', 'StudentEnrollment')

    for m in TransportAttendance.objects.all():
        enrollment = StudentEnrollment.objects.filter(
            student=m.student,
            session__is_active=True
        ).first()

        if enrollment:
            m.enrollment = enrollment
            m.save(update_fields=['enrollment'])


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0092_transportattendance_enrollment'),
    ]

    operations = [
        migrations.RunPython(migrate_transportattendance, reverse_code=migrations.RunPython.noop),
    ]
