# Generated by Django 5.1.4 on 2026-01-20 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0093_migrate_TransportAttendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentdetails',
            name='enrollment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_details', to='registration.studentenrollment'),
        ),
    ]
