# Generated by Django 5.1.4 on 2026-01-20 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0095_alter_feedetails_enrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportdetails',
            name='enrollment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transport_details', to='registration.studentenrollment'),
        ),
    ]
