# Generated by Django 5.1.4 on 2026-01-31 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0096_alter_transportdetails_enrollment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentbatchlink',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='studentbatchlink',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_batch_links', to='registration.studentenrollment'),
        ),
        migrations.AlterUniqueTogether(
            name='studentbatchlink',
            unique_together={('student', 'batch', 'enrollment')},
        ),
    ]
