# Generated by Django 5.1.4 on 2026-02-01 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0098_backfill_enrollment_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentenrollment',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
