# Generated by Django 5.1.4 on 2026-02-02 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0099_studentenrollment_remarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='batches',
        ),
        migrations.RemoveField(
            model_name='student',
            name='class_enrolled',
        ),
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last_year_marks_details',
        ),
        migrations.RemoveField(
            model_name='student',
            name='marksheet_submitted',
        ),
        migrations.RemoveField(
            model_name='student',
            name='program_duration',
        ),
        migrations.RemoveField(
            model_name='student',
            name='sat_score',
        ),
        migrations.RemoveField(
            model_name='student',
            name='subjects',
        ),
    ]
