# Generated by Django 5.1.4 on 2026-02-06 13:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0100_remove_student_batches_remove_student_class_enrolled_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='XPSolvLoginInitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('phone', models.CharField(blank=True, default='', max_length=15)),
                ('client_id', models.CharField(blank=True, default='', max_length=128)),
                ('surface', models.CharField(blank=True, default='', max_length=16)),
                ('attempts', models.PositiveSmallIntegerField(default=1)),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('success', models.BooleanField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('redirect_host', models.CharField(blank=True, default='', max_length=255)),
                ('redirect_path', models.CharField(blank=True, default='', max_length=512)),
                ('upstream_response', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('is_hx', models.BooleanField(default=False)),
                ('session_key', models.CharField(blank=True, default='', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xpsolv_login_init_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='registratio_created_27e3cd_idx'), models.Index(fields=['phone'], name='registratio_phone_d1c240_idx')],
            },
        ),
    ]
