# Generated by Django 5.1.4 on 2026-03-01 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0101_xpsolvlogininitlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedetails',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='registration.student'),
        ),
    ]
