# Generated by Django 5.1.4 on 2026-03-12 07:24

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0018_alter_batch_unique_together_remove_batch_session'),
        ('registration', '0102_alter_feedetails_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('duration_label', models.CharField(blank=True, help_text='Eg: 1-2 Years', max_length=30, null=True)),
                ('target_focus', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('annual_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('surcharge_1_subject_pct', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5)),
                ('surcharge_2_subject_pct', models.DecimalField(decimal_places=2, default=Decimal('7.50'), max_digits=5)),
                ('surcharge_3_subject_pct', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_offerings', to='center.classname')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_offerings', to='registration.academicsession')),
            ],
            options={
                'ordering': ['session', 'class_name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='course_offering',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='registration.courseoffering'),
        ),
        migrations.CreateModel(
            name='CourseOfferingSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_subjects', to='registration.courseoffering')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_offering_subjects', to='center.subject')),
            ],
            options={
                'ordering': ['course_offering', 'subject'],
                'unique_together': {('course_offering', 'subject')},
            },
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='course_offerings', through='registration.CourseOfferingSubject', to='center.subject'),
        ),
        migrations.AlterUniqueTogether(
            name='courseoffering',
            unique_together={('session', 'class_name', 'name')},
        ),
    ]
