# Generated by Django 5.1.4 on 2026-03-12 10:52

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0103_courseoffering_studentenrollment_course_offering_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseoffering',
            name='surcharge_1_subject_pct',
        ),
        migrations.RemoveField(
            model_name='courseoffering',
            name='surcharge_2_subject_pct',
        ),
        migrations.RemoveField(
            model_name='courseoffering',
            name='surcharge_3_subject_pct',
        ),
        migrations.CreateModel(
            name='CourseOfferingSurchargeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_opted_out_subjects', models.PositiveSmallIntegerField(help_text='Applies when opted out subjects (total - selected) are >= this value.')),
                ('surcharge_pct', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentage of full annual fee.', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surcharge_rules', to='registration.courseoffering')),
            ],
            options={
                'ordering': ['course_offering', 'min_opted_out_subjects'],
                'unique_together': {('course_offering', 'min_opted_out_subjects')},
            },
        ),
    ]
