# Generated by Django 5.1.4 on 2026-03-12 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0104_remove_courseoffering_surcharge_1_subject_pct_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseoffering',
            name='description',
        ),
        migrations.RemoveField(
            model_name='courseoffering',
            name='duration_label',
        ),
        migrations.RemoveField(
            model_name='courseoffering',
            name='remarks',
        ),
    ]
