# Generated by Django 5.1.4 on 2026-04-03 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0105_remove_courseoffering_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedetails',
            name='book_gst',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='feedetails',
            name='gst_opted_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feedetails',
            name='transport_gst',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='feedetails',
            name='tuition_gst',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
