# Generated by Django 5.1.4 on 2026-04-04 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0106_gst_fields_on_fee_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedetails',
            name='book_component',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='feedetails',
            name='tuition_component',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
