# Generated by Django 5.1.4 on 2026-04-06 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0107_feedetails_book_component_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicsession',
            name='target',
            field=models.IntegerField(blank=True, help_text='Enrollment target for this session', null=True),
        ),
    ]
