# Generated by Django 5.1.4 on 2025-01-12 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mistake',
            new_name='Remark',
        ),
        migrations.RemoveField(
            model_name='questionresponse',
            name='mistake',
        ),
        migrations.AddField(
            model_name='questionresponse',
            name='remark',
            field=models.ManyToManyField(related_name='remark', to='center.remark'),
        ),
    ]
