# Generated by Django 5.1.4 on 2025-01-17 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0003_rename_mistake_remark_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='testquestion',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='optionalQuestion',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='optional', to='center.testquestion'),
        ),
    ]
