# Generated by Django 5.1.4 on 2025-01-17 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0005_rename_optionalquestion_testquestion_optional_question_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testquestion',
            name='has_optional',
        ),
        migrations.AddField(
            model_name='testquestion',
            name='is_main',
            field=models.BooleanField(default=True),
        ),
    ]
