# Generated by Django 5.1.4 on 2025-01-18 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0007_alter_attendance_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionresponse',
            name='marks_obtained',
            field=models.FloatField(),
        ),
    ]
