# Generated by Django 5.1.4 on 2025-01-20 21:01

import django.db.models.deletion
from django.db import migrations, models

def migrate_remarks(apps, schema_editor):
    QuestionResponse = apps.get_model('center', 'QuestionResponse')
    for response in QuestionResponse.objects.all():
        if response.remark.exists():
            # Set the first remark (or use other logic to pick the correct one)
            response.remark2 = response.remark.first()
            response.save()

class Migration(migrations.Migration):

    dependencies = [
        ('center', '0008_alter_questionresponse_marks_obtained'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionresponse',
            name='remark2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remark2', to='center.remark'),
        ),
        migrations.RunPython(migrate_remarks),
    ]
