# Generated by Django 5.1.4 on 2025-01-20 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0009_questionresponse_remark2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionresponse',
            name='remark',
        ),
    ]
