# Generated by Django 5.1.4 on 2025-01-20 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0010_remove_questionresponse_remark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionresponse',
            old_name='remark2',
            new_name='remark',
        ),
    ]
