# Generated by Django 5.1.4 on 2025-01-20 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0011_rename_remark2_questionresponse_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionresponse',
            name='remark',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remark', to='center.remark'),
        ),
    ]
