# Generated by Django 5.1.4 on 2025-01-24 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0013_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='no_of_questions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='test',
            name='total_max_marks',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='RemarkCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('remark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remark_counts', to='center.remark')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remark_counts', to='center.student')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remark_tests', to='center.test')),
            ],
            options={
                'unique_together': {('student', 'test', 'remark')},
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_questions_attempted', models.IntegerField(default=0)),
                ('total_marks_obtained', models.FloatField(default=0)),
                ('total_max_marks', models.FloatField(default=0)),
                ('percentage', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='center.student')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='center.test')),
            ],
            options={
                'unique_together': {('student', 'test')},
            },
        ),
    ]
