# Generated by Django 5.1.4 on 2026-01-15 11:46

from django.db import migrations


def attach_session_to_batches(apps, schema_editor):
    Batch = apps.get_model('center', 'Batch')
    AcademicSession = apps.get_model('registration', 'AcademicSession')

    active_session = AcademicSession.objects.filter(is_active=True).first()

    if not active_session:
        return

    Batch.objects.filter(session__isnull=True).update(
        session=active_session
    )

class Migration(migrations.Migration):

    dependencies = [
        ('center', '0016_alter_batch_unique_together_batch_session_and_more'),
    ]

    operations = [
        migrations.RunPython(attach_session_to_batches, migrations.RunPython.noop),
    ]
