# Generated by Django 5.1.4 on 2026-01-16 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0017_backfill_batch_sessions'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='batch',
            unique_together={('class_name', 'section', 'subject')},
        ),
        migrations.RemoveField(
            model_name='batch',
            name='session',
        ),
    ]
