# Generated by Django 5.1.4 on 2025-07-17 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0048_alter_installment_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_sequences', to='registration.batch')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_sequences', to='registration.chapter')),
            ],
            options={
                'ordering': ['batch', 'sequence'],
                'unique_together': {('batch', 'chapter', 'sequence')},
            },
        ),
    ]
