# Generated by Django 5.1.4 on 2025-07-17 06:40

from django.db import migrations

def populate_chapter_sequences(apps, schema_editor):
    Chapter = apps.get_model('registration', 'Chapter')
    Batch = apps.get_model('registration', 'Batch')  # Adjust if your Batch model is elsewhere
    ChapterSequence = apps.get_model('lesson', 'ChapterSequence')

    batches = Batch.objects.all()
    for batch in batches:
        chapters = Chapter.objects.filter(subject=batch.subject, class_name=batch.class_name).order_by('chapter_no')
        for chapter in chapters:
            ChapterSequence.objects.create(
                batch=batch,
                chapter=chapter,
                sequence=chapter.chapter_no
            )

def delete_chapter_sequences(apps, schema_editor):
    ChapterSequence = apps.get_model('lesson', 'ChapterSequence')
    ChapterSequence.objects.all().delete()



class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_chapter_sequences, delete_chapter_sequences),
    ]
