# Generated by Django 5.1.4 on 2025-07-17 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0002_populate_chapter_sequences'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('topic', models.CharField(max_length=255)),
                ('homework', models.TextField()),
                ('classwork', models.TextField()),
                ('chapter_sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='lesson.chaptersequence')),
            ],
            options={
                'ordering': ['chapter_sequence__sequence', 'sequence'],
            },
        ),
    ]
