# Generated by Django 5.1.4 on 2025-07-20 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0004_holiday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
