# Generated by Django 5.1.4 on 2025-07-30 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0005_alter_holiday_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='classwork',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='homework',
            field=models.TextField(blank=True, null=True),
        ),
    ]
