# Generated by Django 5.1.4 on 2025-07-31 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0015_remove_homework_batch_remove_homework_student_and_more'),
        ('lesson', '0006_alter_lesson_classwork_alter_lesson_homework'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaptersequence',
            name='chapter_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chaptersequence',
            name='chapter_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chaptersequence',
            name='class_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='center.classname'),
        ),
        migrations.AddField(
            model_name='chaptersequence',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='center.subject'),
        ),
    ]
