# Generated by Django 5.1.4 on 2025-07-31 11:32

from django.db import migrations

def populate_chapter_fields(apps, schema_editor):
    ChapterSequence = apps.get_model('lesson', 'ChapterSequence')
    for cs in ChapterSequence.objects.select_related('chapter'):
        chapter = cs.chapter
        cs.class_name = chapter.class_name
        cs.subject = chapter.subject
        cs.chapter_no = chapter.chapter_no
        cs.chapter_name = chapter.chapter_name
        cs.save()


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0007_chaptersequence_chapter_name_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_chapter_fields),
    ]
