# Generated by Django 5.1.4 on 2025-08-01 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0008_populate_chaptersequence_fields'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chaptersequence',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='chaptersequence',
            name='chapter',
        ),
    ]
