# Generated by Django 5.1.4 on 2025-08-01 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0009_alter_chaptersequence_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chaptersequence',
            name='class_name',
        ),
    ]
