# Generated by Django 5.1.4 on 2025-08-01 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0010_remove_chaptersequence_class_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chaptersequence',
            name='subject',
        ),
    ]
