# Generated by Django 5.1.4 on 2025-08-03 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0012_lecture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lecture',
            options={'ordering': ['-date', 'lesson__chapter_sequence__sequence', 'lesson__sequence']},
        ),
        migrations.AlterUniqueTogether(
            name='lecture',
            unique_together=set(),
        ),
    ]
