# Generated by Django 5.1.4 on 2025-08-14 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0013_alter_lecture_options_alter_lecture_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='LectureMismatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('Cancelled', 'Cancelled'), ('Substitute', 'Substitute'), ('Extra Class', 'Extra Class'), ('Other', 'Other')], max_length=20)),
                ('remark', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mismatches', to='lesson.lesson')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
