# Generated by Django 5.1.4 on 2025-08-18 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0014_lecturemismatch'),
        ('registration', '0055_alter_studenttestremark_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LectureDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecture_dates', to='registration.batch')),
            ],
            options={
                'ordering': ['batch', 'date'],
                'unique_together': {('batch', 'date')},
            },
        ),
    ]
