# Generated by Django 5.1.4 on 2025-08-26 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0015_lecturedate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LectureMismatch',
        ),
    ]
