# Generated by Django 5.1.4 on 2025-04-27 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_baseuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
