# Generated by Django 5.1.4 on 2025-05-11 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_baseuser_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='change_password',
            field=models.BooleanField(default=True),
        ),
    ]
